
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 13;
  public static final int PREFIX = 11;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int POINT = 10;
  public static final int IF = 8;
  public static final int SENTENCE = 14;
  public static final int ELSE = 9;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int RPAREN = 4;
  public static final int SUFFIX = 12;
  public static final int END = 7;
  public static final int LPAREN = 3;
  public static final int BEGIN = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "BEGIN",
  "END",
  "IF",
  "ELSE",
  "POINT",
  "PREFIX",
  "SUFFIX",
  "STRING_LITERAL",
  "SENTENCE"
  };
}

